### PR TITLE
Dev journal

### PR DESCRIPTION
**Pull request by mishkajethwani**
> Description

Made some CSS, JS and HTML changes for better styling and user experience

> Changes Made

- Changed the Roles Fulfilled to include a description of the icons, make the icons clearer and make the checkbox larger
- Fixed Margins for wide screens and mobile devices
- Fixed Date picker overlap
- Changed the markdown to work properly while previewing and editing
- Changed styling of the markdown
- Centralized the Save button
- Fixed styling for Datepicker
- Changed the homepage button to make it consistent with the calendar
- Changed Bug Tracker and Learnings to be consistent with the Roles Fulfilled
- Other Minor CSS and HTML Changes

> Screenshots (if applicable)
Screen Shot 2024-05-30 at 1 41 44 PM

Screen Shot 2024-05-30 at 1 43 29 PM

Screen Shot 2024-05-30 at 1 42 21 PM

> Checklist

Strict PR Policy:

- [x] All automated tests pass locally.
- [x] Manual testing has been performed according to the provided instructions.
- [x] Code follows the project's coding conventions and standards.
- [x] Documentation has been updated to reflect any relevant changes.
- [ ] This PR has been reviewed by at least 2 of the team members.
- [x] It passes all the appropriate Linters

> Additional Notes (if any)

### CODE REVIEW

**Comment by dregmi08** [comment]
I think these changes are really good. Overall, everything looks very consistent but it appears that for the phone layout, the markdown editor border is still black whereas on the wider screen layout it doesn't have the black border. Other than that, I think that these changes are very good and the dev-journal CSS looks very nice

**Comment by mishkajethwani** [comment]
Thank you for pointing that out Drishti!

Just pushed changes to correct that.

**Review by Arnav710 — COMMENTED** [review]
Styling changes including buttons and layout looks good, would be nice to have words in words instead of yyyy-mm-dd. I just changed that!

**Comment by Angelsofttoy** [comment]
I think it looks pretty good as well! The spacing between each icons are a bit uneven when selected, I'll try to see if I could fix it!

**Pull request merged**
