### PR TITLE
dev

### PR DESCRIPTION
**Pull request by Arnav710**
> Description

Created the MVP followed by V1 of the website in addition to writing end to end tests for the same.

> Changes Made

##### Calendar
- **Navigation**: Move through different months seamlessly.
- **Task Viewing**: Click on a day to view the task list for that specific date. Tasks are retrieved from localStorage.
- **Task Management**: Add, edit, and remove tasks for any given day.
- **Saving Tasks**: Click the save button to store tasks in localStorage.

##### Dev Journal
- **Default View**: Opens with the current date by default.
- **Date Picker**: Use the date picker to switch between dates.
- **Markdown Editor**: Write and preview your journal entries using a markdown editor.
  - **Scrolling**: If your content exceeds the viewable area, you can scroll within both the preview and the editor.
  - **Toggle View**: Switch between the editor and the preview using the provided buttons.
- **Role Selection**: Select roles that you fulfilled on a given day.
- **Saving Data**: All input data is saved to localStorage upon clicking the save button.

#### Terminal Shortcuts
To improve accessibility a terminal has been added which allows you to navigate between various pages and do certain tasks on both the calendar and the dev-journal without clicking on the screen.

> Testing

Manually tested the calendar, task-list, dev-journal, and home page to see that behavior matches what is expected. Also wrote comprehensive end to end tests for all features. 

> Screenshots (if applicable)

image

image

image

image

> Checklist

Strict PR Policy:

- [x] All automated tests pass locally.
- [x] Manual testing has been performed according to the provided instructions.
- [x] Code follows the project's coding conventions and standards.
- [x] Documentation has been updated to reflect any relevant changes.
- [ ] This PR has been reviewed by at least 2 of the team members.
- [x] It passes all the appropriate Linters.

> Additional Notes (if any)

### CODE REVIEW

**Review by hdsouza13 — COMMENTED** [review]
Everything is working, the calendar, the task list, the Dev Journal. Saving and deleting data are working. The only thing is that on some pages,  the design cut a little of the page, so you need to scroll a little down to see everything(but I dont see that a big issue).
Devph1
Devph2
Devph3

**Comment by mishkajethwani** [comment]
Everything works properly on my end, including the sentiment analysis, number of tasks displayed, and keyboard shortcuts. The css and html for all three pages looks good as well. PWA works on my end as well. Looks good to be merged into main

**Comment by vishaal-gaddipati** [comment]
Just took a look on my end and everything including the PWA was working, except for the command `md e`. Not sure if this is an issue on my end or a bug.

**Comment by Arnav710** [comment]
> Just took a look on my end and everything including the PWA was working, except for the command `md e`. Not sure if this is an issue on my end or a bug.

The purpose of that command is to switch between editor and preview so it is fine if it does not focus on the editor!

**Pull request merged**
